---
- include_vars: ../../common_vars.yml

- name: Set variables
  set_fact:
    control_plane_dir: '{{playbook_dir}}/resources/control-plane'
    go_bin: '/usr/local/go/bin'
    go_path: "{{ lookup('env', 'HOME') }}/go"

- name: Get toml parser & psql driver for Golang
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ lookup('env', 'GOPATH') }}"
  shell: |
    go get github.com/BurntSushi/toml
    go get gopkg.in/pg.v5

- name: Build Control Plane API
  become: yes
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
  shell: "go build -o {{control_plane_dir}}/snowplow-mini-control-plane-api {{control_plane_dir}}/*.go"

- name: Copy Control Plane API to executables dir
  become: yes
  synchronize:
    src: "{{control_plane_dir}}/snowplow-mini-control-plane-api"
    dest: "{{executables_dir}}"

- name: Build Caddy
  environment:
    PATH: "{{ lookup('env','PATH') }}:{{ go_bin }}"
    GOPATH: "{{ go_path }}"
  shell: |
    export GO111MODULE=on
    cd /home/ubuntu/snowplow/caddy
    go install

- name: Copy Caddy executable to executables dir
  become: yes
  synchronize:
    src: "{{ go_path }}/bin/caddy"
    dest: "{{executables_dir}}"
