---
- include_vars: ../../common_vars.yml

- name: Set variables
  set_fact:
    control_plane_dir: '{{playbook_dir}}/resources/control-plane'

- name: Add Go backports for old versions
  become: yes
  command: sudo add-apt-repository -y ppa:longsleep/golang-backports

- name: Install Go 1.15
  become: yes
  command: sudo apt install golang-1.15-go

- name: Init Go module
  become: yes
  command: /usr/lib/go-1.15/bin/go mod init control-plane

- name: Build Control Plane API
  become: yes
  shell: "/usr/lib/go-1.15/bin/go build -o {{control_plane_dir}}/snowplow-mini-control-plane-api {{control_plane_dir}}/*.go"

- name: Copy Control Plane API to executables dir
  become: yes
  synchronize:
    src: "{{control_plane_dir}}/snowplow-mini-control-plane-api"
    dest: "{{executables_dir}}"
