---
- include_vars: ../../common_vars.yml

- name: Set variables
  set_fact:
    control_plane_dir: '{{playbook_dir}}/resources/control-plane'

- name: Install Go 1.23
  become: yes
  command: sudo apt -y install golang-1.23-go

- name: Build Control Plane API
  become: yes
  shell: "cd {{control_plane_dir}} && /usr/lib/go-1.23/bin/go build -o snowplow-mini-control-plane-api *.go"

- name: Copy Control Plane API to executables dir
  become: yes
  synchronize:
    src: "{{control_plane_dir}}/snowplow-mini-control-plane-api"
    dest: "{{executables_dir}}"
