---
- include_vars: ../../common_vars.yml

- name: Install ca-certificates curl gnupg
  become: yes
  shell: sudo apt-get install ca-certificates curl gnupg --yes

- name: Add Docker’s official GPG key
  become: yes
  shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

- name: Set up Docker repo
  become: yes
  shell: echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list

- name: Install docker-compose
  apt: name=docker-compose state=latest

- name: Copy docker-compose.yml and its environment file
  copy: src={{ item.src }} dest={{ item.dest }} owner=ubuntu group=ubuntu mode=0644
  with_items:
    - { src: '../files/docker-compose.yml', dest: '/home/ubuntu/snowplow/' }
    - { src: '../files/.env', dest: '/home/ubuntu/snowplow/' }

- name: Create & set permissions of elasticsearch data directory
  become: yes
  shell: rm -rf {{main_dir}}/elasticsearch/data && mkdir {{main_dir}}/elasticsearch/data && chown -R 1000:1000 {{main_dir}}/elasticsearch/data

- name: Increase mmap count to recommended 262144 for Elasticsearch
  become: yes
  shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf && service procps restart

- name: Start snowplow mini (docker-compose up)
  become: yes
  shell: cd {{main_dir}} && docker-compose up -d && sleep 20

- name: Wait for Elasticsearch port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9200
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Wait for Kibana port 5601 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 5601
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Create ES indexes
  become: yes
  shell: sh {{init_dir}}/create-es-indices.sh

- name: Create Kibana index patterns
  become: yes
  shell: sh {{init_dir}}/create-kibana-indexes.sh

- name: Create NSQ topics
  become: yes
  shell: |
    curl -X POST localhost:4151/topic/create?topic=RawEvents
    curl -X POST localhost:4151/topic/create?topic=BadEvents
    curl -X POST localhost:4151/topic/create?topic=EnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=BadEnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=PiiEvents

- name: Replace docker-compose.yml based on the platform
  become: yes
  shell: sh {{init_dir}}/compose.sh
