---
- include_vars: ../../common_vars.yml

- name: Wait for Elasticsearch port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9200
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Wait for Kibana port 5601 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 5601
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Create ES indexes
  become: yes
  shell: sh {{init_dir}}/create-es-indices.sh

- name: Create Kibana index patterns
  become: yes
  shell: sh {{init_dir}}/create-kibana-indexes.sh

- name: Create NSQ topics
  become: yes
  shell: |
    curl -X POST localhost:4151/topic/create?topic=RawEvents
    curl -X POST localhost:4151/topic/create?topic=BadEvents
    curl -X POST localhost:4151/topic/create?topic=EnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=BadEnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=PiiEvents

# Cronjob: Clean old docs from 'good' index
- name: Add cronjob to clean old ES 'good' index documents
  cron:
    name: "Crop ES 'good' index older than a week"
    special_time: weekly
    job: >
      /usr/bin/curl -s -X POST http://localhost:9200/good/_delete_by_query
      -H 'Content-Type:application/json'
      -d '{ "query" :{ "range" :{ "collector_tstamp" :{ "lt" :"now-1w/d" } } } }'
      >> /home/ubuntu/snowplow/good_cron.out 2>> /home/ubuntu/snowplow/good_cron.err

# Cronjob: Clean old docs from 'bad' index
- name: Add cronjob to clean old ES 'bad' index documents
  cron:
    name: "Crop ES 'bad' index older than a week"
    special_time: weekly
    job: >
      /usr/bin/curl -s -X POST http://localhost:9200/bad/_delete_by_query
      -H 'Content-Type:application/json'
      -d '{ "query" :{ "range" :{ "data.failure.timestamp" :{ "lt" :"now-1w/d" } } } }'
      >> /home/ubuntu/snowplow/bad_cron.out 2>> /home/ubuntu/snowplow/bad_cron.err

# Cronjob: Clean NSQ data
- name: Add cronjob to clean NSQ data
  cron:
    name: "Crop NSQ data"
    special_time: weekly
    job: /bin/rm -rf /home/ubuntu/snowplow/nsq-data/*

- name: Replace docker-compose.yml based on the platform
  become: yes
  shell: sh {{init_dir}}/compose.sh
