---
- include_vars: ../../common_vars.yml

- name: Remove containerd
  apt: name=containerd.io state=absent

- name: Install docker compose v2
  apt: name=docker-compose-v2 state=latest

- name: Copy docker-compose.yml and its environment file
  copy: src={{ item.src }} dest={{ item.dest }} owner=ubuntu group=ubuntu mode=0644
  with_items:
    - { src: '../files/docker-compose.yml', dest: '/home/ubuntu/snowplow/' }
    - { src: '../files/.env', dest: '/home/ubuntu/snowplow/' }

- name: Create & set permissions of elasticsearch data directory
  become: yes
  shell: rm -rf {{main_dir}}/elasticsearch/data && mkdir {{main_dir}}/elasticsearch/data && chown -R 1000:1000 {{main_dir}}/elasticsearch/data

- name: Increase mmap count to recommended 262144 for Elasticsearch
  become: yes
  shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf && service procps restart

- name: Remove cache to open space for docker
  become: yes
  shell: rm -rf /var/cache/*

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -50
  register: dq

- debug: var=dq.stdout_lines

- name: df -h
  become: yes
  shell: df -h
  register: df2

- debug: var=df2.stdout_lines

- name: remove some unused packages to open space for docker
  become: yes
  shell: apt-get remove libllvm18 python3-botocore libclang-cpp18 vim-runtime git python3-twisted python-babel-localedata python3-pygments -y


- name: apt autoremove to open space for docker
  become: yes
  shell: apt autoremove -y

- name: df -h
  become: yes
  shell: df -h
  register: df

- debug: var=df.stdout_lines

- name: Start snowplow mini (docker compose up)
  become: yes
  shell: cd {{main_dir}} && docker compose up -d && sleep 20

- name: df -h
  become: yes
  shell: df -h
  register: df

- debug: var=df.stdout_lines

- name: Wait for Elasticsearch port 9200 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 9200
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Wait for Kibana port 5601 to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: 5601
    delay: 10
    sleep: 5
    connect_timeout: 60

- name: Create ES indexes
  become: yes
  shell: sh {{init_dir}}/create-es-indices.sh

- name: Create Kibana index patterns
  become: yes
  shell: sh {{init_dir}}/create-kibana-indexes.sh

- name: Create NSQ topics
  become: yes
  shell: |
    curl -X POST localhost:4151/topic/create?topic=RawEvents
    curl -X POST localhost:4151/topic/create?topic=BadEvents
    curl -X POST localhost:4151/topic/create?topic=EnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=BadEnrichedEvents
    curl -X POST localhost:4151/topic/create?topic=PiiEvents

- name: Replace docker-compose.yml based on the platform
  become: yes
  shell: sh {{init_dir}}/compose.sh
