---
- include_vars: ../../common_vars.yml

- name: Pre cleanup disk usage
  become: yes
  shell: df -h
  register: dfpre

- debug: var=dfpre.stdout_lines

- name: Clear apt and package manager caches
  become: yes
  shell: |
    apt-get clean
    rm -rf /var/lib/apt/lists/*

- name: Remove man pages, locales, docs, cache
  become: yes
  shell: |
    rm -rf /usr/share/man/*
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/info/*
    rm -rf /var/cache/man /var/cache/fonts
    rm -rf /root/.cache/*
    rm -rf /home/*/.cache/*

- name: remove some unused packages to open space for docker
  become: yes
  ignore_errors: true
  shell: |
    apt-get remove --yes --fix-broken --quiet --purge \
      iso-codes \
      ieee-data \
      libllvm18 \
      libclang-cpp18 \
      vim-runtime \
      git \
      python-babel-localedata \
      libicu74 \
      locales

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -100
  register: dq

- debug: var=dq.stdout_lines

- name: Clean journal logs
  become: yes
  shell: journalctl --flush --rotate --vacuum-time=1s

## ubuntu 24 specific steps below

- name: Disable snapd services
  become: true
  shell: |
    systemctl disable snapd.service snapd.socket snapd.seeded.service || true
    apt-get purge -y snapd || true
  ignore_errors: true

- name: Mask hibinit-agent to avoid boot hang
  become: true
  systemd:
    name: hibinit-agent.service
    enabled: false
    masked: true
  ignore_errors: true

##################

- name: Autoremove orphaned packages
  become: yes
  shell: apt-get autoremove --purge -y

- name: Post cleanup disk usage
  become: yes
  shell: df -h /
  register: dfpost

- debug: var=dfpost.stdout_lines
