---
- include_vars: ../../common_vars.yml

- name: Remove cache to open space for docker
  become: yes
  shell: rm -rf /var/cache/*

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -100
  register: dq

- debug: var=dq.stdout_lines

- name: df -h
  become: yes
  shell: df -h
  register: df2

- debug: var=df2.stdout_lines

- name: remove some unused packages to open space for docker
  become: yes
  shell: |
    apt-get remove --yes --fix-broken --quiet --purge \
      iso-codes \
      ieee-data \
      libllvm18 \
      python3-botocore \
      libclang-cpp18 \
      vim-runtime \
      git \
      python3-twisted \
      python-babel-localedata \
      python3-pygments \
      python3-cryptography \
      python3-setuptools \
      libicu74 \
      locales \
      intel-microcode \
      libpython3.12t64 \
      libmagic-mgc

- name: apt autoremove to open space for docker
  become: yes
  shell: apt autoremove -y

- name: df -h
  become: yes
  shell: df -h
  register: df

- debug: var=df.stdout_lines

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -50
  register: dq2

- debug: var=dq2.stdout_lines
