---
- include_vars: ../../common_vars.yml

- name: Remove some directories to open space for docker
  become: yes
  shell: |
    rm -rf /var/cache/*
    rm -rf /usr/share/man/*
    rm -rf /var/log/*
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/locale/*
    rm -rf /tmp/*

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -100
  register: dq

- debug: var=dq.stdout_lines

- name: df -h
  become: yes
  shell: df -h
  register: df2

- debug: var=df2.stdout_lines

- name: remove some unused packages to open space for docker
  become: yes
  shell: |
    apt-get remove --yes --fix-broken --quiet --purge \
      iso-codes \
      ieee-data \
      libllvm18 \
      python3-botocore \
      libclang-cpp18 \
      vim-runtime \
      git \
      python3-twisted \
      python-babel-localedata \
      python3-pygments \
      python3-cryptography \
      python3-setuptools \
      libicu74 \
      locales \
      intel-microcode \
      libpython3.12t64 \
      libmagic-mgc

- name: see unused kernel packages
  become: yes
  shell: |
    dpkg -l 'linux-*' | \
    sed '/^ii/!d;/'"$(uname -r | sed 's/\(.*\)-\([^0-9]\+\)/\1/')"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d'
  register: uk

- debug: var=uk.stdout_lines

- name: remove unused kernel packages
  become: yes
  shell: |
    dpkg -l 'linux-*' | \
    sed '/^ii/!d;/'"$(uname -r | sed 's/\(.*\)-\([^0-9]\+\)/\1/')"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | \
    xargs -r sudo apt remove --purge -y

- name: apt autoremove to open space for docker
  become: yes
  shell: apt autoremove -y

- name: df -h
  become: yes
  shell: df -h
  register: df

- debug: var=df.stdout_lines

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -50
  register: dq2

- debug: var=dq2.stdout_lines
