---
- include_vars: ../../common_vars.yml

- name: Clear apt and package manager caches
  become: yes
  shell: |
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*

- name: Remove man pages, locales, docs, cache
  become: yes
  shell: |
    rm -rf /usr/share/man/*
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/info/*
    rm -rf /usr/share/locale/*
    rm -rf /var/cache/*
    rm -rf /root/.cache/*
    rm -rf /home/*/.cache/*

- name: Aggressively purge non-core python3-* packages
  become: yes
  shell: |
    dpkg-query -W -f='${Package}\n' | \
    grep '^python3-' | \
    grep -vE '^(python3$|python3-minimal$|python3\.[0-9]+$|python3\.[0-9]+-minimal$)' | \
    xargs -r apt-get purge -y
  ignore_errors: true

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -100
  register: dq

- debug: var=dq.stdout_lines

- name: df -h
  become: yes
  shell: df -h
  register: df2

- debug: var=df2.stdout_lines

- name: remove some unused packages to open space for docker
  become: yes
  ignore_errors: true
  shell: |
    apt-get remove --yes --fix-broken --quiet --purge \
      iso-codes \
      ieee-data \
      libllvm18 \
      python3-botocore \
      libclang-cpp18 \
      vim-runtime \
      git \
      python3-twisted \
      python-babel-localedata \
      python3-pygments \
      python3-cryptography \
      python3-setuptools \
      libpython3.12t64 \
      libmagic-mgc \
      python3-launchpadlib \
      python3-netaddr \
      python3-chardet \
      python3-rich \
      python3-boto3 \
      python3-gi \
      python3-pyasn1-modules \
      python3-oauthlib \
      python3-jinja2 \
      python3-yaml \
      python3-jsonschema \
      python3-apport \
      python3-serial \
      python3-urllib3 \
      python3-babel

- name: Autoremove orphaned packages
  become: yes
  shell: apt-get autoremove --purge -y

- name: Clean journal logs
  become: yes
  shell: journalctl --flush --rotate --vacuum-time=1s

- name: Final disk usage
  become: yes
  shell: df -h /
  register: df_final

- debug: var=df_final.stdout_lines
