---
- include_vars: ../../common_vars.yml

- name: Clear apt and package manager caches
  become: yes
  shell: |
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*

- name: Remove man pages, locales, docs, cache
  become: yes
  shell: |
    rm -rf /usr/share/man/*
    rm -rf /usr/share/doc/*
    rm -rf /usr/share/info/*
    rm -rf /usr/share/locale/*
    rm -rf /var/cache/man /var/cache/fonts
    rm -rf /root/.cache/*
    rm -rf /home/*/.cache/*

- name: list non-core python3-* packages
  become: yes
  shell: |
    dpkg-query -W -f='${Package}\n' | \
    grep '^python3-' | \
    grep -vE '^(python3$|python3-minimal$|python3\.[0-9]+$|python3\.[0-9]+-minimal$)' | \
    grep -vE '^(python3-(apt|systemd|dbus|gi|netplan|netifaces|cryptography|openssl|debian|distro|setuptools|pkg-resources|six|requests|urllib3|yaml|idna|dateutil))$'
  ignore_errors: true
  register: agg

- debug: var=agg.stdout_lines

- name: Selectively purge non-essential python3-* packages
  become: yes
  shell: |
    dpkg-query -W -f='${Package}\n' | \
    grep '^python3-' | \
    grep -vE '^(python3$|python3-minimal$|python3\.[0-9]+$|python3\.[0-9]+-minimal$)' | \
    grep -vE '^(python3-(apt|systemd|dbus|gi|netplan|netifaces|cryptography|openssl|debian|distro|setuptools|pkg-resources|six|requests|urllib3|yaml|idna|dateutil))$' | \
    xargs -r apt-get purge -y
  ignore_errors: true

- name: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n
  become: yes
  shell: dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n | tail -100
  register: dq

- debug: var=dq.stdout_lines

- name: df -h
  become: yes
  shell: df -h
  register: df2

- debug: var=df2.stdout_lines

- name: remove some unused packages to open space for docker
  become: yes
  ignore_errors: true
  shell: |
    apt-get remove --yes --fix-broken --quiet --purge \
      iso-codes \
      ieee-data \
      libllvm18 \
      libclang-cpp18 \
      vim-runtime \
      git \
      python-babel-localedata \
      libicu74 \
      locales

- name: Autoremove orphaned packages
  become: yes
  shell: apt-get autoremove --purge -y

- name: Clean journal logs
  become: yes
  shell: journalctl --flush --rotate --vacuum-time=1s

## ubuntu 24 specific steps below

- name: Disable snapd services
  become: true
  shell: |
    systemctl disable snapd.service snapd.socket snapd.seeded.service || true
    apt-get purge -y snapd || true
  ignore_errors: true

- name: Mask hibinit-agent to avoid boot hang
  become: true
  systemd:
    name: hibinit-agent.service
    enabled: false
    masked: true

- name: Disable systemd-networkd-wait-online to avoid boot hang
  become: true
  systemd:
    name: systemd-networkd-wait-online.service
    enabled: false
    masked: true

##################

- name: Final disk usage
  become: yes
  shell: df -h /
  register: df_final

- debug: var=df_final.stdout_lines
