#!/bin/sh

### BEGIN INIT INFO
# Provides:             snowplow_mini
# Required-Start:       $docker
# Required-Stop:        $docker
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Snowplow Mini Services
### END INIT INFO

set -e

YAMLFILE=/home/ubuntu/snowplow/docker-compose.yml
OPTS="-f $YAMLFILE"
UPOPTS="-d --no-recreate"

up_cmd="cd /home/ubuntu/snowplow && sudo docker-compose up $UPOPTS"
stop_cmd="cd /home/ubuntu/snowplow && sudo docker-compose stop"
down_cmd="cd /home/ubuntu/snowplow && sudo docker-compose down"

name="snowplow_mini"
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

case "$1" in
    start)
        echo -n "Starting Snowplow Mini..."
        $up_cmd >> "$stdout_log" 2>> "$stderr_log" &
        echo "done"
        ;;

    stop)
        echo -n "Stopping Snowplow Mini..."
        $stop_cmd >> "$stdout_log" 2>> "$stderr_log" &
        echo "done"
        ;;

    restart)
        echo -n "Restarting Snowplow Mini..."
        $down_cmd >> "$stdout_log" 2>> "$stderr_log" &
        $up_cmd >> "$stdout_log" 2>> "$stderr_log" &
        echo "done"
        ;;

    *)
        echo "Usage: /etc/init.d/snowplow_mini {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
