---
- name: apply all scripts
  hosts: all

  roles:
    - typescript
    - packer
    - sp_mini_1_create_dirs
    - sp_mini_3_build_go_projects
    - sp_mini_4_setup_apps
    - sp_mini_5_build_ui
    - sp_mini_6_copy_ui_folders
    - sp_mini_7_setup_init
    - docker
