---
# This playbook is used for provisioning of the AMI
# UI and executables file are made ready locally in Github Actions
# They are only copied into the AMI here
- name: apply all scripts
  hosts: all

  roles:
    - sp_mini_1_create_dirs
    - sp_mini_4_setup_apps
    - sp_mini_6_copy_ui_folders
    - sp_mini_7_setup_init
    - cleanup
    - docker