---
# This playbook is used for provisioning of the vagrant machine.
# All tools for compilation of the Control Plane API, Caddy Server
# and UI is setup to the vagrant machine in here.
# Additionally, Snowplow Mini environment is made ready to use locally.
- name: apply all scripts
  hosts: all

  roles:
    - ansible-go
    - nodejs
    - typescript
    - packer
    - sp_mini_1_create_dirs
    - sp_mini_2_install_postgresl
    - sp_mini_3_build_go_projects
    - sp_mini_4_setup_apps
    - sp_mini_5_build_ui
    - sp_mini_6_copy_ui_folders
    - sp_mini_7_setup_init
    - sp_mini_8_configure
